"""Static type stubs for atomr_ontology.core."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable, Mapping, Optional, overload

class Iri:
    def __init__(self, value: str) -> None: ...
    @classmethod
    def from_unchecked(cls, value: str) -> "Iri": ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...

class _IdLike:
    @classmethod
    def new_random(cls) -> "_IdLike": ...
    @classmethod
    def content_address(cls, input: bytes) -> "_IdLike": ...
    def to_bytes(self) -> bytes: ...
    def __str__(self) -> str: ...

class NodeId(_IdLike): ...
class EdgeId(_IdLike): ...
class RecordId(_IdLike): ...
class AxiomId(_IdLike): ...

class Cardinality:
    @classmethod
    def one(cls) -> "Cardinality": ...
    @classmethod
    def optional(cls) -> "Cardinality": ...
    @classmethod
    def many(cls) -> "Cardinality": ...
    @classmethod
    def bounded(cls, min: int, max: Optional[int]) -> "Cardinality": ...
    @property
    def min(self) -> int: ...
    @property
    def max(self) -> Optional[int]: ...

class Datatype:
    @classmethod
    def string(cls) -> "Datatype": ...
    @classmethod
    def integer(cls) -> "Datatype": ...
    @classmethod
    def float_(cls) -> "Datatype": ...
    @classmethod
    def bool_(cls) -> "Datatype": ...
    @classmethod
    def date_time(cls) -> "Datatype": ...
    @classmethod
    def iri(cls) -> "Datatype": ...
    @classmethod
    def bytes_(cls) -> "Datatype": ...
    @classmethod
    def json(cls) -> "Datatype": ...
    @property
    def name(self) -> str: ...

class PropertyValue:
    @classmethod
    def string(cls, v: str) -> "PropertyValue": ...
    @classmethod
    def integer(cls, v: int) -> "PropertyValue": ...
    @classmethod
    def float_(cls, v: float) -> "PropertyValue": ...
    @classmethod
    def bool_(cls, v: bool) -> "PropertyValue": ...
    @classmethod
    def iri(cls, v: Iri) -> "PropertyValue": ...
    @classmethod
    def date_time(cls, v: datetime) -> "PropertyValue": ...
    @classmethod
    def bytes_(cls, v: bytes) -> "PropertyValue": ...
    @classmethod
    def null(cls) -> "PropertyValue": ...
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> Any: ...

class Property:
    name: str
    value: PropertyValue

class PropertyType:
    def __init__(self, name: str, datatype: Datatype, cardinality: Cardinality,
                 iri: Optional[Iri] = ..., description: Optional[str] = ...) -> None: ...
    name: str
    datatype: Datatype
    cardinality: Cardinality
    iri: Optional[Iri]
    description: Optional[str]

class NodeType:
    def __init__(self, name: str) -> None: ...
    def with_iri(self, iri: Iri) -> "NodeType": ...
    def with_supertype(self, name: str) -> "NodeType": ...
    def with_property(self, prop: PropertyType) -> "NodeType": ...
    def with_description(self, desc: str) -> "NodeType": ...
    @property
    def name(self) -> str: ...
    @property
    def iri(self) -> Optional[Iri]: ...
    @property
    def supertypes(self) -> list[str]: ...
    @property
    def properties(self) -> list[PropertyType]: ...

class EdgeType:
    def __init__(self, name: str) -> None: ...
    def with_iri(self, iri: Iri) -> "EdgeType": ...
    def with_domain(self, name: str) -> "EdgeType": ...
    def with_range(self, name: str) -> "EdgeType": ...
    def functional(self, value: bool = ...) -> "EdgeType": ...
    @property
    def name(self) -> str: ...
    @property
    def iri(self) -> Optional[Iri]: ...

class Schema:
    def __init__(self) -> None: ...
    def declare_node_type(self, ty: NodeType) -> None: ...
    def declare_edge_type(self, ty: EdgeType) -> None: ...
    def node_type(self, name: str) -> Optional[NodeType]: ...
    def edge_type(self, name: str) -> Optional[EdgeType]: ...
    @property
    def node_types(self) -> dict[str, NodeType]: ...
    @property
    def edge_types(self) -> dict[str, EdgeType]: ...

class Namespace:
    def __init__(self, prefix: str, base: Iri) -> None: ...
    prefix: str
    base: Iri

class Vocabulary:
    def __init__(self) -> None: ...
    @classmethod
    def with_standard_bindings(cls) -> "Vocabulary": ...
    def bind(self, prefix: str, base: Iri) -> None: ...
    def expand_curie(self, curie: str) -> Optional[Iri]: ...

class Node:
    def __init__(self, type_name: str) -> None: ...
    @classmethod
    def from_iri(cls, iri: Iri, type_name: str) -> "Node": ...
    def with_property(self, name: str, value: Any) -> "Node": ...
    def with_type(self, name: str) -> "Node": ...
    def has_type(self, name: str) -> bool: ...
    @property
    def id(self) -> NodeId: ...
    @property
    def iri(self) -> Optional[Iri]: ...
    @property
    def types(self) -> list[str]: ...
    @property
    def properties(self) -> dict[str, PropertyValue]: ...

class Edge:
    @classmethod
    def between(cls, source: NodeId, label: str, target: NodeId) -> "Edge": ...
    def with_property(self, name: str, value: Any) -> "Edge": ...
    @property
    def id(self) -> EdgeId: ...
    @property
    def source(self) -> NodeId: ...
    @property
    def target(self) -> NodeId: ...
    @property
    def label(self) -> str: ...
    @property
    def properties(self) -> dict[str, PropertyValue]: ...

class Record:
    def __init__(self, kind: str) -> None: ...
    def with_field(self, name: str, value: Any) -> "Record": ...
    @property
    def id(self) -> RecordId: ...
    @property
    def kind(self) -> str: ...

class AxiomKind:
    @classmethod
    def sub_class_of(cls, sub: str, sup: str) -> "AxiomKind": ...
    @classmethod
    def equivalent_class(cls, left: str, right: str) -> "AxiomKind": ...
    @classmethod
    def disjoint_with(cls, left: str, right: str) -> "AxiomKind": ...
    @classmethod
    def functional(cls, property: str) -> "AxiomKind": ...
    @classmethod
    def transitive(cls, property: str) -> "AxiomKind": ...
    @classmethod
    def symmetric(cls, property: str) -> "AxiomKind": ...
    @classmethod
    def domain(cls, property: str, class_: str) -> "AxiomKind": ...
    @classmethod
    def range(cls, property: str, class_: str) -> "AxiomKind": ...
    @classmethod
    def inverse_of(cls, left: str, right: str) -> "AxiomKind": ...
    @property
    def name(self) -> str: ...

class Axiom:
    def __init__(self, kind: AxiomKind) -> None: ...
    def with_provenance(self, prov: Any) -> "Axiom": ...
    @property
    def id(self) -> AxiomId: ...
    @property
    def kind(self) -> AxiomKind: ...

class Ontology:
    def __init__(self) -> None: ...
    def declare_node_type(self, name: str) -> None: ...
    def declare_edge_type(self, name: str) -> None: ...
    def upsert_node(self, node: Node) -> NodeId: ...
    def upsert_edge(self, edge: Edge) -> EdgeId: ...
    def upsert_axiom(self, axiom: Axiom) -> None: ...
    def node(self, id: NodeId) -> Optional[Node]: ...
    def edge(self, id: EdgeId) -> Optional[Edge]: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def nodes(self) -> dict[NodeId, Node]: ...
    @property
    def edges(self) -> dict[EdgeId, Edge]: ...
    @property
    def vocabulary(self) -> Vocabulary: ...
