"""Static type stubs for atomr_ontology.embed."""
from __future__ import annotations

from typing import Awaitable

from .core import Ontology

class HashEmbedder:
    def __init__(self, dim: int) -> None: ...
    @property
    def dimensions(self) -> int: ...
    @property
    def label(self) -> str: ...
    def embed(self, text: str) -> Awaitable[list[float]]: ...

class VectorRecord:
    def __init__(self, iri: str, vector: list[float]) -> None: ...
    @property
    def iri(self) -> str: ...
    @property
    def vector(self) -> list[float]: ...

class VectorIndex:
    def __init__(self) -> None: ...
    @classmethod
    def with_dimensions(cls, dim: int) -> "VectorIndex": ...
    def insert(self, record: VectorRecord) -> None: ...
    def search(self, query: list[float], top_k: int) -> list[tuple[str, float]]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...

class EmbeddingResolver:
    def __init__(self, embedder: HashEmbedder) -> None: ...
    def ingest_ontology(self, ontology: Ontology) -> Awaitable[int]: ...
    def propose(self, surface: str, top_k: int) -> Awaitable[list[tuple[str, float]]]: ...
    def __len__(self) -> int: ...
