"""Static type stubs for atomr_ontology.extract."""
from __future__ import annotations

from typing import Awaitable, Optional

from .core import Edge, Node, NodeId, Record
from .provenance import Activity

class Prompt:
    @classmethod
    def user(cls, body: str) -> "Prompt": ...
    def with_system(self, body: str) -> "Prompt": ...
    def with_max_tokens(self, n: int) -> "Prompt": ...
    @property
    def system(self) -> Optional[str]: ...
    @property
    def user(self) -> str: ...
    @property
    def max_tokens(self) -> Optional[int]: ...

class Backend:
    @property
    def label(self) -> str: ...
    def complete(self, prompt: Prompt) -> Awaitable[str]: ...
    def batch_complete(self, prompts: list[Prompt]) -> Awaitable[list[tuple[bool, str]]]: ...
    def with_lru_cache(self, capacity: int) -> "Backend": ...
    def with_content_cache(self) -> "Backend": ...

class ExtractStage:
    @property
    def label(self) -> str: ...

class TermCandidate:
    surface: str
    score: float
    category: Optional[str]

class EntityCandidate:
    surface: str
    iri: Optional[str]
    type_name: str
    score: float
    is_new: bool

class RelationCandidate:
    source: str
    label: str
    target: str
    score: float

class TermExtractor:
    def __init__(self, backend: Backend) -> None: ...
    def with_system_prompt(self, prompt: str) -> "TermExtractor": ...
    def extract(self, document: str) -> Awaitable[tuple[list[TermCandidate], Activity]]: ...

class EntityResolver:
    def __init__(self, backend: Backend) -> None: ...
    def with_system_prompt(self, prompt: str) -> "EntityResolver": ...
    def resolve(self, terms: list[TermCandidate]) -> Awaitable[tuple[list[EntityCandidate], Activity]]: ...
    @staticmethod
    def into_nodes(candidates: list[EntityCandidate], iri_required: bool = ...) -> list[Node]: ...

class RelationExtractor:
    def __init__(self, backend: Backend) -> None: ...
    def with_system_prompt(self, prompt: str) -> "RelationExtractor": ...
    def extract(self, document: str, entities: list[EntityCandidate]) -> Awaitable[tuple[list[RelationCandidate], Activity]]: ...
    @staticmethod
    def into_edges(candidates: list[RelationCandidate], surface_to_id: dict[str, NodeId]) -> list[Edge]: ...

class RecordExtractor:
    def __init__(self, backend: Backend) -> None: ...
    def extract(self, document: str, kind: str) -> Awaitable[tuple[list[Record], Activity]]: ...
