"""Static type stubs for atomr_ontology.persist."""
from __future__ import annotations

from typing import Awaitable

class MemCheckpointer:
    def __init__(self) -> None: ...
    @property
    def label(self) -> str: ...

class FileCheckpointer:
    def __init__(self, path: str) -> None: ...
    @property
    def label(self) -> str: ...

class PersistentStore:
    @classmethod
    def from_memory(cls, checkpointer: MemCheckpointer) -> Awaitable["PersistentStore"]: ...
    @classmethod
    def from_file(cls, checkpointer: FileCheckpointer) -> Awaitable["PersistentStore"]: ...
    def version(self) -> int: ...
