"""Static type stubs for atomr_ontology.provenance."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from .core import NodeId, EdgeId, RecordId

class AgentKind:
    @classmethod
    def software(cls) -> "AgentKind": ...
    @classmethod
    def person(cls) -> "AgentKind": ...
    @property
    def name(self) -> str: ...

class AgentRef:
    @classmethod
    def software(cls, id: str, label: str) -> "AgentRef": ...
    @classmethod
    def person(cls, id: str, label: str) -> "AgentRef": ...
    @property
    def id(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def kind(self) -> AgentKind: ...

ProvAgent = AgentRef

class ProvenanceId:
    @classmethod
    def new_random(cls) -> "ProvenanceId": ...
    def to_bytes(self) -> bytes: ...

class ProvEntity:
    def __init__(self, label: str, digest: Optional[str] = ...) -> None: ...
    @property
    def id(self) -> ProvenanceId: ...
    @property
    def label(self) -> str: ...
    @property
    def digest(self) -> Optional[str]: ...

class Activity:
    @classmethod
    def started(cls, label: str) -> "Activity": ...
    def by(self, agent: AgentRef) -> "Activity": ...
    def with_attribute(self, name: str, value: Any) -> "Activity": ...
    def finish(self) -> "Activity": ...
    @property
    def id(self) -> ProvenanceId: ...
    @property
    def label(self) -> str: ...
    @property
    def started_at(self) -> datetime: ...
    @property
    def ended_at(self) -> Optional[datetime]: ...

class ProvenanceLog:
    def __init__(self) -> None: ...
    def record_activity(self, activity: Activity) -> None: ...
    def record_entity(self, entity: ProvEntity) -> None: ...
    @property
    def activities(self) -> dict[ProvenanceId, Activity]: ...
    @property
    def entities(self) -> dict[ProvenanceId, ProvEntity]: ...
