"""Static type stubs for atomr_ontology.rdf."""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from .core import Iri, Ontology

class Subject:
    @classmethod
    def iri(cls, value: Iri) -> "Subject": ...
    @classmethod
    def blank(cls, label: str) -> "Subject": ...
    @classmethod
    def blank_n(cls, n: int) -> "Subject": ...
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> object: ...

class Object:
    @classmethod
    def iri(cls, value: Iri) -> "Object": ...
    @classmethod
    def blank(cls, label: str) -> "Object": ...
    @classmethod
    def literal(cls, lexical: str, datatype: Iri, language: Optional[str] = ...) -> "Object": ...
    @classmethod
    def xsd_string(cls, value: str) -> "Object": ...
    @classmethod
    def xsd_integer(cls, value: int) -> "Object": ...
    @classmethod
    def xsd_double(cls, value: float) -> "Object": ...
    @classmethod
    def xsd_boolean(cls, value: bool) -> "Object": ...
    @classmethod
    def xsd_date_time(cls, value: datetime) -> "Object": ...
    @property
    def kind(self) -> str: ...
    @property
    def lexical(self) -> Optional[str]: ...
    @property
    def datatype(self) -> Optional[Iri]: ...
    @property
    def language(self) -> Optional[str]: ...

class Triple:
    def __init__(self, subject: Subject, predicate: Iri, object: Object) -> None: ...
    @property
    def subject(self) -> Subject: ...
    @property
    def predicate(self) -> Iri: ...
    @property
    def object(self) -> Object: ...

class Quad:
    def __init__(self, subject: Subject, predicate: Iri, object: Object, graph: Iri) -> None: ...
    @property
    def graph(self) -> Iri: ...

class Class:
    name: str
    iri: Iri
    super_classes: list[Iri]

class Individual:
    iri: Iri
    types: list[Iri]

class ObjectProperty:
    name: str
    iri: Iri

class DataProperty:
    name: str
    iri: Iri

def to_rdf(ontology: Ontology) -> list[Triple]: ...
def from_rdf(triples: list[Triple]) -> Ontology: ...
def turtle_write(ontology: Ontology) -> str: ...
def ntriples_write(ontology: Ontology) -> str: ...
def jsonld_write(ontology: Ontology) -> str: ...
def turtle_parse(input: str) -> list[Triple]: ...
def turtle_read(input: str) -> Ontology: ...
def ntriples_parse(input: str) -> list[Triple]: ...
def ntriples_read(input: str) -> Ontology: ...
def jsonld_parse(input: str) -> list[Triple]: ...
def jsonld_read(input: str) -> Ontology: ...
def iri_unchecked(value: str) -> Iri: ...
