"""Static type stubs for atomr_ontology.reason."""
from __future__ import annotations

from .core import Ontology
from .provenance import Activity

class RuleSet:
    @classmethod
    def standard(cls) -> "RuleSet": ...
    @classmethod
    def empty(cls) -> "RuleSet": ...
    def __len__(self) -> int: ...

class Reasoner:
    def __init__(self) -> None: ...
    @classmethod
    def with_max_iterations(cls, max: int) -> "Reasoner": ...
    def run(self, ontology: Ontology) -> tuple[int, int, int, Activity]: ...
    def materialize(self, ontology: Ontology) -> Activity: ...
