"""Static type stubs for atomr_ontology.store."""
from __future__ import annotations

from typing import Any, Awaitable, Optional

from .core import Axiom, Edge, EdgeId, Node, NodeId, Ontology
from .provenance import Activity, ProvenanceId, ProvenanceLog

class NodePattern:
    @classmethod
    def any(cls) -> "NodePattern": ...
    def bind(self, name: str) -> "NodePattern": ...
    def typed(self, name: str) -> "NodePattern": ...
    def with_property(self, name: str, value: Any) -> "NodePattern": ...
    def with_id(self, id: NodeId) -> "NodePattern": ...
    def or_(self, alt: "NodePattern") -> "NodePattern": ...
    def not_(self, neg: "NodePattern") -> "NodePattern": ...

class EdgePattern:
    @classmethod
    def any(cls) -> "EdgePattern": ...
    def bind(self, name: str) -> "EdgePattern": ...
    def labeled(self, label: str) -> "EdgePattern": ...
    def with_property(self, name: str, value: Any) -> "EdgePattern": ...
    def repeat(self, min: int, max: int) -> "EdgePattern": ...

class TraversalStep:
    @classmethod
    def outbound(cls, edge: EdgePattern, target: NodePattern) -> "TraversalStep": ...
    @classmethod
    def inbound(cls, edge: EdgePattern, target: NodePattern) -> "TraversalStep": ...

class TraversalPlan:
    def __init__(self, seed: NodePattern) -> None: ...
    @classmethod
    def from_seed(cls, seed: NodePattern) -> "TraversalPlan": ...
    def outbound(self, edge: EdgePattern, target: NodePattern) -> "TraversalPlan": ...
    def inbound(self, edge: EdgePattern, target: NodePattern) -> "TraversalPlan": ...
    def return_(self, columns: list[str]) -> "TraversalPlan": ...
    def order_by(self, binding: str) -> "TraversalPlan": ...
    def order_by_desc(self, binding: str) -> "TraversalPlan": ...
    def skip(self, n: int) -> "TraversalPlan": ...
    def limit(self, n: int) -> "TraversalPlan": ...

class MatchRow:
    def __init__(self) -> None: ...
    @property
    def nodes(self) -> dict[str, NodeId]: ...
    @property
    def edges(self) -> dict[str, EdgeId]: ...

class OntologyDelta:
    def __init__(self, nodes: Optional[list[Node]] = ..., edges: Optional[list[Edge]] = ...,
                 axioms: Optional[list[Axiom]] = ...) -> None: ...
    def with_node(self, node: Node) -> "OntologyDelta": ...
    def with_edge(self, edge: Edge) -> "OntologyDelta": ...
    def with_axiom(self, axiom: Axiom) -> "OntologyDelta": ...

class StoreDiff:
    added_nodes: list[NodeId]
    removed_nodes: list[NodeId]
    added_edges: list[EdgeId]
    removed_edges: list[EdgeId]

class MemStore:
    def __init__(self) -> None: ...
    @classmethod
    def from_ontology(cls, ontology: Ontology) -> "MemStore": ...
    def upsert_node(self, node: Node) -> Awaitable[NodeId]: ...
    def upsert_edge(self, edge: Edge) -> Awaitable[EdgeId]: ...
    def upsert_axiom(self, axiom: Axiom) -> Awaitable[None]: ...
    def node(self, id: NodeId) -> Awaitable[Optional[Node]]: ...
    def edge(self, id: EdgeId) -> Awaitable[Optional[Edge]]: ...
    def match_pattern(self, pattern: NodePattern) -> Awaitable[list[MatchRow]]: ...
    def traverse(self, plan: TraversalPlan) -> Awaitable[list[MatchRow]]: ...
    def snapshot(self) -> Awaitable[Ontology]: ...
    def diff(self, other: Ontology) -> Awaitable[StoreDiff]: ...
    def commit_with_provenance(self, delta: OntologyDelta, activity: Activity) -> Awaitable[ProvenanceId]: ...
    def provenance(self) -> Awaitable[ProvenanceLog]: ...
