"""Static type stubs for atomr_ontology.testkit."""
from __future__ import annotations

from .core import Ontology
from .extract import Backend

class MockBackend:
    def __init__(self) -> None: ...
    @classmethod
    def with_label(cls, label: str) -> "MockBackend": ...
    def enqueue(self, response: str) -> None: ...
    @property
    def label(self) -> str: ...

def toy_corpus() -> list[str]: ...
def toy_org_ontology() -> Ontology: ...
def assert_axiom_present(ontology: Ontology, sub: str, sup: str) -> None: ...
def assert_subclass_of(ontology: Ontology, sub: str, sup: str) -> None: ...
