"""Static type stubs for atomr_ontology.version."""
from __future__ import annotations

from typing import Optional

from .core import Ontology

class CommitId:
    def __str__(self) -> str: ...

class MergeStrategy:
    Ours: "MergeStrategy"
    Theirs: "MergeStrategy"
    Union: "MergeStrategy"

class VersionedStore:
    def __init__(self) -> None: ...
    def commit(self, message: str, author: str, snapshot: Ontology) -> CommitId: ...
    def branch(self, name: str) -> None: ...
    def checkout(self, name: str) -> None: ...
    def merge(self, other: str, strategy: MergeStrategy) -> CommitId: ...
    def as_of(self, id: CommitId) -> Optional[Ontology]: ...
    def branches(self) -> list[str]: ...
    def current(self) -> str: ...
