"""Static type stubs for atomr_ontology.viz."""
from __future__ import annotations

from .core import Ontology
from .provenance import ProvenanceLog

def render_ontology_dot(ontology: Ontology) -> str: ...
def render_ontology_mermaid(ontology: Ontology) -> str: ...
def render_provenance_dot(log: ProvenanceLog) -> str: ...
def render_provenance_mermaid(log: ProvenanceLog) -> str: ...
